accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), 
		name='login'),
	url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
	url(r'^signup/$', views.Signup.as_view(), name='signup'),
]

chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

chatApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as base_views


from accounts import urls as accounts_urls
from chat import urls as chat_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.HomePage.as_view(), name='home'),
    path('accounts/', include(accounts_urls)),
    path('chat/', include(chat_urls)),
]

accounts/models.py
from django.db import models
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

	def __str__(self):
		return f"{self.username}"

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.urls import reverse


# Create your models here.
User = get_user_model()

class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    posted_at = models.DateTimeField(auto_now=True, null=True)


    def __str__(self):
        return str(self.message)

    def get_absolute_url(self):
	      return reverse('chat:all')

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
	fields = ("username", "password1", "password2")
	model = get_user_model()

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['username'].help_text = None		
		self.fields['password1'].help_text = None
		self.fields['password2'].help_text = None

chat/forms.py
from django import forms
from .models import Chat


class ChatForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ('message', )

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UserCreateForm
from django.views.generic import CreateView

# Create your views here.
class Signup(CreateView):
	form_class = UserCreateForm
	success_url = reverse_lazy('accounts:login')
	template_name = 'accounts/signup.html'

chat/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from .forms import ChatForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Chat
from django.utils import timezone

# Create your views here.


class ChatCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    form_class = ChatForm
    model = Chat

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ChatListView(LoginRequiredMixin, ListView):
    model = Chat

    def get_queryset(self):
        return Chat.objects.filter(posted_at__lte=timezone.now()).order_by('posted_at')

chatApp/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
	template_name = 'index.html'

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Chattr- Login Portal
{% endblock title %}


{% block content %}

		<div class="row">
			<div class="col-md-4">
				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}

					<input type="submit" value='Login' class="btn btn-outline-primary">
				</form>
			</div>

			<div class="col-md-7">
				<h4>Welcome Back To <i>VIBEz!</i> Login And Start chatting!</h4><hr>
				<p class="description">
					Welcome back there <i>VIBEz!</i> looks like you were logged out the last session. just to ensure your security please login again.
				</p>
			</div>
		</div>
{% endblock content %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block title %}

    Chattr- Signup Portal

{% endblock title %}

{% block content %}
    <div class="row">
			<div class="col-md-4">
				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}

					<input type="submit" value='Signup' class="btn btn-outline-primary">
				</form>
			</div>

			<div class="col-md-7">
				<h4>Be Ready To Become A Part Of <i>VIBEz</i> Global Community</h4><hr>
				<p class="description">
					We are the Chattrs!

					Well, Hello and welcome to the <i>VIBEz</i> chat App global community! here thousands of people chat and discuss whatever they want
					this is a virtual heaven for people who like to be social and want a size that is easy to operate with and co-orperate with!
					This is Me, Ramandeep kaur The Developer and Maintaner/Admin of this site if at any time you want to co-orperate or report
					any bugs about this site please report it here- <a href="https://ramanbhutta7274.gmail.com">ramanbhutta7274@gmail.com</a>. Hope so will help
					to develope a more better and strong community- Ramandeep kaur
				</p>
			</div>
		</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

		
		<!-- Title -->
		<title>{% block title %} {% endblock title %}</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
		
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:wght@300;400;500;600;700;800;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
		
		<!-- Style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

		<!-- Favicon -->
		<link rel="shortcut icon" type="image/svg" href="{% static 'favicon.svg' %}">


</head>
<body style="background: #202020; color: whitesmoke;">


		<!-- Nav -->
		<nav class="navbar navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: orangered; font-weight: 300; box-shadow: 0px 0px 20px 5px #000; font-family: 'Ubuntu', sans-serif;">
		  <a class="navbar-brand" href="{% url 'home' %}">VIBEz</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  {% if user.is_authenticated %}
		      
		      <div class="collapse navbar-collapse" id="navbarNav">
		        <ul class="navbar-nav">
		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'chat:all' %}">Chat</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
		          </li>
		        </ul>
		      </div>
		  
		  {% else %}
		  	<div class="collapse navbar-collapse" id="navbarNav">
		        <ul class="navbar-nav">
		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
		          </li>
		        </ul>
		      </div>
		  {% endif %}
		</nav>


		<!-- Content -->
		<div class="container" style="margin-top: 50px;">{% block content %}{% endblock content %}</div>
		<br><br><hr><br><br>





		<button onclick="topFunction()" id="go-to-top" title="Go to top">&#8593;</button>
		<script type="text/javascript">
			//Get the button:
			go_to_top = document.getElementById("go-to-top");

			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function() {scrollFunction()};

			function scrollFunction() {
			  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 200) {
			    go_to_top.style.display = "block";
			  } else {
			    go_to_top.style.display = "none";
			  }
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
			  document.body.scrollTop = 0; // For Safari
			  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
			}
		</script>
</body>
</html>

templates/chat/chat_form.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}

    	<br><input type="submit" value="Post" class="btn btn-lg btn-outline-primary">
    </form>
{% endblock content %}

templates/chat/chat_list.html
{% extends "base.html" %}

{% block title %}
    Chat App- All Chats
{% endblock title %}

{% block content %}
    <a href="/chat"><button class="btn btn btn-primary"><i class="fa fa-refresh" aria-hidden="true"></i>
    Rerfresh For Any New Chats</button></a><br><br><br>

    {% for chat in object_list %}


    	<div class="chat" style="width: 80%; background: rgb(220, 20, 60); box-shadow: 2px 0px 25px 20px #111;">
    		{% if chat.user.is_superuser %}
    		    

    		    <small class="chat-user-special"> {{ chat.user }}- Admin </small>

    		
    		{% else %}

						<small class="chat-user"> {{ chat.user }} </small>    		    

    		{% endif %}
    		<p><b class="chat-content">{{ chat|linebreaks }}</b></p>
    		<small class="chat-date">{{ chat.posted_at }}</small>
    	</div><br><br>

    {% empty %}
    <h1 class="heading">No Chats Yet Be The First To Message!</h1><br>

    {% endfor %}
    <br><a href="{% url 'chat:new' %}"><button class="btn btn-outline-primary">New Message</button></a>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block title %}
    Index
{% endblock title %}

{% block content %}

		{% if not user.is_authenticated %}
<h1 class="heading" style="text-align: center;">Welcome To <i>VIBEz!</i></h1><br><hr class="hr"><br>
		    <h5>Table Of Contents</h5><br>
	     	| <a href="#introduction" class="link">Introduction</a> |
	    	<a href="#help" class="link">Getting Help</a> |
	    	<a href="#about-us" class="link">About Us</a> |
	    	<a href="#thanks" class="link">Thank You</a>  | <br><hr style="background: #555;"><br>
		    <!-- Other Stuff -->

		    <div class="wrapper" style="text-align: center;">
		    			<div id="introduction">
    				    <br><br><br><h3 class="sub-heading">Wondering Where To Chat? This Is The Place For You!</h3>
    				    <p class="description">
    				    	Welcome To The All The New Chatting Platform <i>VIBEz!</i>  This A Global Community Where You and your freinds family any one chat! any time, anywhere!
    				    	make friends do chatting and what not you can do over here!
    					  </p>
    					  <br><br>
    				    <h3 class="sub-heading">Is It A Nightmare, That Your Activity Is Been Tracked?</h3>
    				    <p class="description">
    				    	And The Most Importantly "Is my information and activity is been tracked ?". No! Even a piece of your valuable privacy is
    				    	been tracked. because your privacy is our duty.
    				    </p>
    				    <br><br>
    				    <h3 class="sub-heading">Ready To Experience The Change?</h3>
    				    <p class="description">
							So what are thinking about? join the <i>vibez</i> community now! and experience the change!
    				    </p>
    				    <br><br><br>
		    			</div>
		    			<div id="help">
		    				<br><br><br><h3 class="heading">Getting Help</h3><br>
		    				<p class="description">This is Me, Ramandeep kaur The Developer and Maintaner/Admin of this site if at any time you want to co-orperate or report any bugs about this site please report it here- ramanbhutta7274@gmail.com. Hope so will help to develope a more better and strong community- Ramandeep kaur<p><br>
		    				<br><br><br>
		    			</div>
		    			<div id="about-us">
		    				<br><br><br><h3 class="heading">About Us</h3><br>
		    				<p class="description">We are the <i>Vibez!</i> Well, Hello and welcome to the chat App global community! here thousands of people chat and discuss whatever they want this is a virtual heaven for people who like to be social and want a size that is easy to operate with and co-orperate with! This is Me, Ramandeep kaur The Developer and Maintaner/Admin of this site if at any time you want to co-orperate or report any bugs about this site please report it here- ramanbhutta7274@gmail.com. Hope so will help to develope a more better and strong community-Ramandeep kaur</p><br><br>
		    			</div><br><br><br>
		    			<div id="thanks">
		    				<br><br><br><h3 style="font-family: 'Poppins', sans-serif;">Thanks For Visting Us!</h3><br><br><br>
		    			</div>
		    </div>
		    <br><br>































		{% else %}
		    <h1 class="heading" style="text-align: center;">Welcome Back, {{ user }}!</h1><br><hr class="hr"><br><br>
		    <h2 class="normal">You Are Now Logged In To VIBEz!</h2><br><hr><br>
		    <h4 class="normal">What Would You Like To Do ?</h4><br>

		  | <a href="{% url 'chat:all' %}" class="link">Do Chatting</a> |
		    <a href="{% url 'accounts:logout' %}" class="link">Logout</a> |
		    <a href="#explore" class="link">Explore Our Site</a> |
		    <a href="#introduction" class="link">Introduction</a> |
	    	<a href="#help" class="link">Getting Help</a> |
	    	<a href="#about-us" class="link">About Us</a> |
	    	<a href="#thanks" class="link">Thank You</a>  | <br><hr style="background: #555;"><br>

		    <div id="explore">

                <div class="wrapper" style="text-align: center;">
		    			<div id="introduction">
    				    <br><br><br><h3 class="sub-heading">Wondering Where To Chat? This Is The Place For You!</h3>
    				    <p class="description">
    				    	Welcome To The All The New Chattr! This A Global Community Where You and your freinds family any one chat! any time, anywhere!
    				    	make friends do chatting and what not you can do over here!
    					  </p>
    					  <br><br>
    				    <h3 class="sub-heading">Is It A Nightmare, That Your Activity Is Been Tracked?</h3>
    				    <p class="description">
    				    	And The Most Importantly "Is my information and activity is been tracked ?". No! Even a piece of your valuable privacy is
    				    	been tracked. because your privacy is our duty.
    				    </p>
    				    <br><br>
    				    <h3 class="sub-heading">Ready To Experience The Change?</h3>
    				    <p class="description">
    				        So what are thinking about? join the chattr community now! and experience the change!
    				    </p>
    				    <br><br><br>
		    			</div>
		    			<div id="help">
		    				<br><br><br><h3 class="heading">Getting Help</h3><br>
		    				<p class="description">This is Me, Ramandeep kaur The Developer and Maintaner/Admin of this site if at any time you want to co-orperate or report any bugs about this site please report it here- ramanbhutta7274@gmail.com. Hope so will help to develope a more better and strong community- Ramandeep kaur<p><br>
		    				<br><br><br>
		    			</div>
		    			<div id="about-us">
		    				<br><br><br><h3 class="heading">About Us</h3><br>
		    				<p class="description">We are the Vibez! Well, Hello and welcome to the chattrs global community! here thousands of people chat and discuss whatever they want this is a virtual heaven for people who like to be social and want a size that is easy to operate with and co-orperate with! This is Me, Ramandeep kaur The Developer and Maintaner/Admin of this site if at any time you want to co-orperate or report any bugs about this site please report it here- ramanbhutta7274@gmail.com. Hope so will help to develope a more better and strong community-Ramandeep kaur</p><br><br>
		    			</div><br><br><br>
		    			<div id="thanks">
		    				<br><br><br><h3 style="font-family: 'Poppins', sans-serif;">Thanks For Visting Us!</h3><br><br><br>
		    			</div>
		    </div>

		    	<br><br>
		    </div>
		{% endif %}

{% endblock content %}